[package]
name = "athena-slides"
version = "1.0.1"
entrypoint = "src/lib.typ"
authors = ["Ernesto Martínez <https://ecomaikgolf.com>", "Marcel Schnideritsch"]
license = "MIT"
description = "Theme based on an unofficial ISEC TUGraz slides template"
repository = "https://github.com/nodezeroat/typst-athena-slides-template/"
categories = ["presentation"]
disciplines = ["computer-science", "engineering"]
keywords = []
compiler = "0.13.1"

[template]
path = "template"
entrypoint = "slides.typ"
thumbnail = "thumbnail.png"
